### ISSUE TITLE
watch error

### ISSUE THREAD

**Issue by bsr203** [chriskjaer/prototype-seed#1]
Hello,
The seed looks really great because of the extended documentation and clean way of organizing tasks and configuration. couple of questions though.

1.
I like the fact that the sass files include styleguide documentation, but wonder how tested it is. I would prefer an actively used, tested library considering the variation in browser version etc. can you please comment about the origin of styles defined there.
1.  build error
   on  a fresh install, (clone, npm install, bower install), I get following error when running `gulp`

```
$ bower install
bsr[~/.../prototype-seed] [master] $ gulp
[06:57:37] Using gulpfile ~/.../prototype-seed/gulpfile.js
[06:57:37] Starting 'clean'...
[06:57:37] Finished 'clean' after 5.44 ms
[06:57:37] Starting 'default'...
[06:57:37] Starting 'clean'...
[06:57:37] Finished 'default' after 1.22 ms
[06:57:37] Finished 'clean' after 1.22 ms
[06:57:37] Starting 'browser-sync'...
[06:57:37] Starting 'js'...
[06:57:37] Starting 'css'...
[06:57:37] 'css' errored after 755 μs
[06:57:37] Error in plugin 'gulp-watch'
Message:
    glob should be String or Array, not object
[06:57:37] Finished 'browser-sync' after 100 ms
[BS] 0 file changed ()
[06:57:37] Finished 'js' after 109 ms
[BS] Local URL: http://localhost:3000
[BS] External URL: http://192.168.2.4:3000
[BS] Serving files from: build/
```
1. styleguide

how to start the styleguide. 
I ran an http-server at `prototype-seed/build/styleguide` or opened the index file. but, the script, style path looks wrong if I am on `prototype-seed/build/styleguide`  directory

```
  <script src="../../assets/scripts/vendor.js" type="text/javascript"></script>
```

but style sheet is not generated because of same watch error

```
gulp css
[07:16:02] Working directory changed to ~/Work/Programming/web/gulp/samples/prototype-seed
[07:16:06] Using gulpfile ~/Work/Programming/web/gulp/samples/prototype-seed/gulpfile.js
[07:16:06] Starting 'css'...
[07:16:06] 'css' errored after 1.38 ms
[07:16:06] Error in plugin 'gulp-watch'
Message:
    glob should be String or Array, not object

```

**Comment by bsr203** [comment]
the watch error was due to change in gulp-watch task. Below change solved the error in css build

```
gulp.task('css', function() {
   gulp.src(SOURCE + STYLES + '*.scss')
        .pipe(watch(SOURCE + STYLES + '*.css', function(files) {
  //watch({glob: SOURCE + STYLES + '*.scss'}, function(files) {
    return files.pipe(sass({
        errLogToConsole: true
      }))
      .pipe(prefix("last 1 version", "> 1%", "ie 9")
        .on('error', function (error) {
          console.warn(error.message);
        })
      )
      .pipe(gulp.dest(BUILD + STYLES))
      .pipe(browserSync.reload({stream: true}));
  }));
});

```

changed the asset links for style-guide to

```
<script src="../assets/scripts/vendor.js" type="text/javascript"></script>
  <link rel="stylesheet" href="public/kss.css">
  <link rel="stylesheet" href="../assets/styles/main.css">

```

not sure how you run it though

thanks again for your wrok on this

**Comment by chriskjaer** [comment]
Thanks for spotting that error!
I've changed all the gulp tasks to use the new gulp-watch api.

I've personally and professionally used and perfected this structure for the last couple of years and I wouldn't consider this a library but rather a curated list of tools, best-practices and asset structures wrapped into a neat package ready to use.

If you see any parts that you would like tests for or other improvements, I'm accepting pull requests :)

**Regarding the styleguide:**
When you do a normal `gulp` command a BrowserSync server will be started at http://0.0.0.0:3000 serving the files in the build folder. The kss-task compiles the styleguide to build/styleguide, which means the styleguide should be available from http://0.0.0.0:3000/styleguide and then the paths should be correct.

**Comment by bsr203** [comment]
thanks.. one qn..
I saw you use, `gulp.watch` and `gulp-watch`. 

```
gulp.task('css', function() {
  var FILES = SOURCE + STYLES + '*.scss';
  gulp.src(FILES)
    .pipe(watch(FILES, function(files) {
   ....

gulp.task('watch', ['browser-sync'], function () {
  gulp.watch(SOURCE + STYLES + '**/*.scss',['css', 'kss']);
..
})
```

is there a side effect on doing that (as if I do `gulp watch`, it goes through both watches)?  I read on `gulp-watch` that one of the use case is to filter out only changed files. is that the reason you use it? I also  see `gulp-changed` uses as in [Google Web Kit](https://github.com/google/web-starter-kit/blob/material-sprint/gulpfile.js#L89). Do you think that is a better approach. I am moving from Grunt to Gulp so bit new to this. I see from `jade` task you removed this duplication, but not from some others. Any reason.

Also, can we do incremental compilation of jade files with your setup. This is kind of a requirement for me as I have quite a bit of template files. Thanks again for your patience and effort on this.

Cheers.
bsr.

**Comment by chriskjaer** [comment]
You can read about the new watch api here https://github.com/floatdrop/gulp-watch/blob/master/docs/readme.md -- the last example is showing the way I'm doing it here. It basically gives us incremental rebuild after the initial build.

But there was some issues when using it in combination with jade.

I haven't looked into gulp-changed that much. The last time I used it it was frequently erroring out when I added new files while gulp was running... but that was way before Google released their webkit so it might have gotten better.

I've built projects with 40+ jade files quite quickly without any incremental compilation, but if you're looking for speedy incremental builds I would recommend using gulp-cached + gulp-remember or maybe even gulp-changed.

**Comment by bsr203** [comment]
thanks chris..
